### ISSUE TITLE
Missing Metadata

### ISSUE THREAD

**Issue by simon-donike** [eo4geocourses/FSU-Jena_SAR-Data-for-Flood-Mapping#4]

**Comment by martyna-stelmaszczuk-gorska** [comment]
Hallo Simon,

Soll ich alle Metadaten ausfüllen? 

		<span property="dc:title"> ??????? </span>
		<span property="dc:creator"> ??????? </span>
		<span property="dc:subject"> ??????? </span>
		<span property="dc:abstract"> ??????? </span>
		<span property="dc:tableOfContents"> ??????? </span>
		<span property="dc:desription"> ??????? </span>
		<span property="dc:contributor"> ??????? </span>
		<span property="dc:created"> ??????? </span>
		<span property="dc:type">InteractiveResource</span>
		<span property="dc:format">html</span>
		<span property="dc:language">EN</span>
		<span property="dc:SizeOrDuration">90min</span>
		<span property="dc:audience">students and professionals</span>
		<span property="dc:educationLevel">EQF 6</span>
		<span property="dc:source"> ??????? </span>
		<span property="dc:rightsHolder"> ??????? </span>
		<span property="dc:license">CC BY-SA 4.0</span>

Viele Grüße
Martyna

**Comment by simon-donike** [comment]
Hallo Martyna,
danke für die schnelle Antwort, gerne! Wichtig ist sind vor allem die relations:
`<meta property="dc:relation" content="eo4geo:XXXXX" />`

Danke 👍 
VG Simon

**Comment by martyna-stelmaszczuk-gorska** [comment]
Aaa, ok. Danke!
<meta property="dc:relation" content="eo4geo:" />
<meta property="dc:relation" content="eo4geo:" />
<meta property="dc:relation" content="eo4geo:" />	

Ich werde wahrscheinlich in Evas Video herausfinden, was ich dort eingeben soll? Leider erinnere ich mich nicht mehr.

**Comment by martyna-stelmaszczuk-gorska** [comment]
<meta property="dc:relation" content="eo4geo:" />
		<meta property="dc:relation" content="eo4geo:" />
		<meta property="dc:relation" content="eo4geo:" />

**Comment by simon-donike** [comment]
Die [BoK](https://bok.eo4geo.eu/GIST) (Unter-)Konzepte sind gefragt, in dem Pfad wie sie auch im Browser erscheinen.

Bsp.:  Image Preprocessing (IP) -> Image Understanding (IP3) ->  Image Segmentation (IP3-5) -> Spatial Autocorrelation -> IP3-5-7

Wenn man auf der Website zu den Konzepten klickt, steht dieser Code aber auch ganz hinten im Link: https://bok.eo4geo.eu/IP3-5-7

Beispielhaft sollte das dann so aussehen: 
```
		<link rel="dc:relation" href="eo4geo:IP3-11" />
		<link rel="dc:relation" href="eo4geo:TA13-5-1" />
		<link rel="dc:relation" href="eo4geo:TA14" />
		<link rel="dc:relation" href="eo4geo:TA14-2" />
```

Anhand der Codes werden die Materialien dann auf der Website eingeordnet und thematisch sortiert, sowie ein Donut-Graph erstellt der zeigt wie intensiv welche Konzepte behandelt werden. Nachdem alles Metadaten eingetragen sind kann die Präsentation in den Katalog übernommen werden. 

VG Simon

**Comment by martyna-stelmaszczuk-gorska** [comment]
Danke!

**Comment by martyna-stelmaszczuk-gorska** [comment]
Das habe ich alles geschrieben aber leider als Kommentar ... Ich kopiere die Informationen nach oben:

**Comment by martyna-stelmaszczuk-gorska** [comment]
gemacht:-)
